[package]
name = "piaf-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.piaf]
path = ".."
features = ["std"]

[[bin]]
name = "parse_edid"
path = "fuzz_targets/parse_edid.rs"
test = false
doc = false
bench = false

[[bin]]
name = "capabilities_static"
path = "fuzz_targets/capabilities_static.rs"
test = false
doc = false
bench = false
